spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: root
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
auth:
  jwt:
    secret: ${SECRET_KEY}
    exp:
      access: ${JWT_ACCESS_TOKEN_EXP}
    header: Authorization
    prefix: Bearer
server:
  port: 3002